bdeproject/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('vitrine.urls', namespace="vitrine")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        )

vitrine/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('vitrine.views',
    url(r'^json/(?P<json>\w+)/(?P<tri>[\w|\W]+)', 'json'),
    url(r'^galerie/(?P<nom_galerie>[\w|\W]+)', 'galerie', name="galerie"),
    url(r'^$', 'accueil', name="accueil"),
)

vitrine/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime


class Image(models.Model):
    titre = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='galerie')

    def apercu(self):
        return u'<img style="width:100px" src="{0}" />'.format(self.image.url)
    apercu.allow_tags = True

    def __unicode__(self):
        if self.titre == None :
            return u'Image {0}'.format(str(self.id))
        return self.titre

class Actu (models.Model):
    titre = models.CharField(max_length=200)
    contenu = models.TextField()
    image = models.ForeignKey(Image, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def apercu(self):
        if bool(self.image):
            return u'<img style="width:100px" src="{0}" />'.format(self.image.image.url)
        return u''
    apercu.allow_tags = True

    def __unicode__(self):
        return u'{0} - {1}'.format(self.titre,timezone.localtime(self.date).strftime("%d/%m/%Y %H:%M"))

class Event(models.Model):
    titre = models.CharField(max_length=200)
    contenu = models.TextField()
    date = models.DateTimeField()
    image = models.ForeignKey(Image, null=True)
    lieu = models.CharField(max_length=200, null=True, blank=True)
    date_ajout = models.DateTimeField(auto_now_add=True)

    def apercu(self):
        if bool(self.image):
            return u'<img style="width:100px" src="{0}" />'.format(self.image.image.url)
        return u''
    apercu.allow_tags = True

    def __unicode__(self):
        acroche = ""
        if self.date < timezone.now():
            acroche = "eu "
        return u'{0} - A {1}lieu le {2} - publié le {3}'.format(self.titre, acroche, timezone.localtime(self.date).strftime("%d/%m/%Y %H:%M"), timezone.localtime(self.date_ajout).strftime("%d/%m/%Y %H:%M"))

class Contact(models.Model):
    email = models.EmailField()
    adresse = models.CharField(max_length=200)
    id_facebook = models.CharField(max_length=200)
    profile_instagram = models.CharField(max_length=200)

    def __unicode__(self):
        return self.email+" - "+self.adresse

class Galerie(models.Model):
    nom = models.CharField(max_length=200,primary_key=True)
    images = models.ManyToManyField(Image)

    def apercu(self):
        apercu = u''
        for image in self.images.all():
            apercu += image.apercu()
        return apercu
    apercu.allow_tags = True

    def __unicode__(self):
        return self.nom

class Membre(models.Model):
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='membres',default="membres/default.svg")
    status = models.CharField(max_length=50, null=True, blank=True)
    rang = models.IntegerField()

    def apercu(self):
        return u'<img style="width:100px" src="{0}" />'.format(self.photo.url)
    apercu.allow_tags = True

    def __unicode__(self):
        return self.prenom + " " + self.nom

vitrine/views.py
import datetime
from django.shortcuts import render
from vitrine.models import Actu, Event, Contact, Membre, Galerie
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.utils import timezone, simplejson
from django.shortcuts import render
from django.views.decorators.cache import never_cache

class JsonResponse(HttpResponse):
    def __init__(self, content, mimetype='application/json', status=None, content_type=None):super(JsonResponse, self).__init__(content=simplejson.dumps(content),mimetype=mimetype,status=status,content_type=content_type,)

@never_cache
def json(request, json, tri):
    if json == "actu" and tri == "all":
        return JsonResponse(
            news_to_dico(Actu.objects.all().order_by('-date')))
    elif json == "event" and tri == "historique":
        return JsonResponse(
            news_to_dico( Event.objects.filter(date__lt = timezone.now()).order_by('-date') ))
    elif json == "event" and tri == "prochainement":
        return JsonResponse(
            news_to_dico(Event.objects.filter(date__gte = timezone.now()).order_by('date') ))
    elif json =="event" and tri == "all":
        return JsonResponse(
           news_to_dico(Event.objects.all().order_by('-date') ))
    elif json == "contact" and tri == "all":
        return JsonResponse(contact_to_dico(Contact.objects.all()[:1]))
    elif json == "news":
        return JsonResponse([{"event":Event.objects.filter(date_ajout__gte = datetime.datetime.fromtimestamp(float(tri)/1000)).count(),
                             "actu":Actu.objects.filter(date__gte = datetime.datetime.fromtimestamp(float(tri)/1000)).count()}])
    elif json == "galerie":
        if tri == "all":
            return JsonResponse(galerie_to_dico(Galerie.objects.all().order_by('nom')))
        else:
            if len(Galerie.objects.filter(nom = tri)) > 0:
                return JsonResponse(images_to_dico(Galerie.objects.filter(nom = tri)[0].images.all()))
            else:
                return JsonResponse([])



    return JsonResponse([])

def accueil(request):
    events = list(Event.objects.all().filter(date__gte= timezone.now()).order_by('date')) + list(Event.objects.all().filter(date__lt = timezone.now()).order_by('-date'))
    galeries = []
    for galerie in Galerie.objects.all():
        galeries += [{"nom_galerie":galerie.nom,"titre_image":galerie.images.all()[0].titre,"url_image":galerie.images.all()[0].image.url}]
    return render(request, "base.html", {"actus":Actu.objects.all().order_by('-date')[:2],
                                            "events":events[:2],
                                            "galeries":galeries,
                                            "membres":Membre.objects.all().order_by('rang','nom'),
                                            "contacts":Contact.objects.all()[:1]})


def galerie(request, nom_galerie):
    galerie = Galerie.objects.filter(nom = nom_galerie)
    print(len(galerie))
    if(len(galerie)>0):
        return render(request, "galerie_mobile.html", {"galerie":galerie[0]})
    else:
        raise Http404

def news_to_dico(models):
    dicoArray = []
    for model in models:
        dico = {"titre":model.titre,"contenu":model.contenu,"date":timezone.localtime(model.date).strftime("%d/%m/%Y %H:%M")}
        if type(model) is Event:
                        if bool(model.lieu):
                                dico.update({"lieu":model.lieu})
                        else:
                                dico.update({"lieu":""})
        if bool(model.image):
                        dico.update({"image":model.image.image.url})
        else:
                        dico.update({"image":""})
        dicoArray += [dico]

    return dicoArray

def contact_to_dico(models):
    return {"email":models[0].email,"adresse":models[0].adresse,"id_facebook":models[0].id_facebook,"profile_instagram":models[0].profile_instagram}

def galerie_to_dico(galeries):
    galerieArray = []
    for  galerie in galeries:
        dico = {}
        images = []
        for image in galerie.images.all():
            imageTitre = image.titre
            if imageTitre is None:
                imageTitre = ""
            images += [{"titre":imageTitre,"url":image.image.url}]
        dico.update({"nom":galerie.nom})
        dico.update({"images":images})
        galerieArray += [dico]
    return galerieArray

def images_to_dico(images):
    imageArray = []
    for image in images:
        imageTitre = image.titre
        if imageTitre is None:
            imageTitre = ""
        imageArray += [{"titre":imageTitre,"url":image.image.url}]
    return imageArray

vitrine/templates/actuevent.html
<div id="home">
	<div id="wrap-home"><!--
	--><div id="actu">
			<div class="wrap-title">
				<h1>Actualités</h1>
			</div>
			<div class="wrap-liste-article">
				<div class="liste-article">{% for article in actus%}<!----><div class="article">
					<div class="article-image-mask">
						<img src="{{ article.image.image.url }}"/>
					</div>
						<h3>{{ article.titre }}</h3>
						<div class="wrap-article-content">
							<div class="article-meta">
								<div class="article-date">
									{{ article.date|date:"j F o G:i" }}
								</div>
							</div>
							<div class="wrap-description">
								<div class="description">
										{{ article.contenu|urlize|linebreaksbr }}
								</div>
							</div>
						</div>
					</div>{% endfor %}
				</div>
			</div>
		</div><!--
		--><div id="event">
			<div class="wrap-title">
				<h1>Événements</h1>
			</div>
			<div class="wrap-liste-article">
				<div class="liste-article">{% for event in events %}<!----><div class="article">
						<div class="article-image-mask">
							<img src="{{ event.image.image.url }}"/>
						</div>
						<h3>{{ event.titre }}</h3>
						<div class="wrap-article-content">
							<div class="article-meta">
								<div class="article-date">
									{{ event.date|date:"j F o G:i" }}
								</div>
								<div class="article-lieu">
									{{ event.lieu }}
								</div>
							</div>
							<div class="wrap-description">
								<div  class="description">
								 {{ event.contenu|urlize|linebreaksbr }}
								</div>
							</div>
						</div>
					</div>{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>

vitrine/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <!--[if lt IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <meta charset="utf-8">
        <title>BDE MMI</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css" charset="utf-8">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bde_flex.css" charset="utf-8">
        <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
        <script src="{{ STATIC_URL }}js/swipe.js"></script>
        <script src="{{ STATIC_URL }}js/bde.js"></script>
    </head>
    <body>
	    <header id="navigation">
        {% block header %}
        <nav>
          <a href="#wrap-home"><img src="{{ STATIC_URL }}img/ic_my_library_books.svg"/><span>News</span></a>
          <a href="#wrap-diapo"><img src="{{ STATIC_URL }}img/ic_collections.svg"/><span>Galerie</span></a>
          <a href="#team"><img src="{{ STATIC_URL }}img/ic_people.svg"/><span>L'équipe</span></a>
          <a href="#contact"><img src="{{ STATIC_URL }}img/ic_public.svg"/><span>Contact</span></a>
        </nav>
		{% endblock %}
        </header>

		<div id="logo">
            <img class="hidden-phone" id="go_articles" src="{{ STATIC_URL }}img/arrow.svg" alt="go to news">
        </div>

		<div id="main">
		{% block main %}
			{% include 'actuevent.html' %}
			{% include 'diapo.html' %}
			{% include 'team.html' %}
		{% endblock %}

			<footer>
			{% block footer %}
				{% include 'footer.html' %}
			{% endblock %}
			</footer>
		</div>
    </body>
</html>

vitrine/templates/diapo.html
<div id="wrap-skew">
	<div id="wrap-diapo">
		<div id="diapo" class="swipe">
			<div class="swipe-wrap">
				{% for galerie in galeries%}
				<div>

					<a href="{% url 'vitrine:galerie' galerie.nom_galerie %}">
						<img src="{{galerie.url_image}}" alt="{{galerie.titre_image}}"/></a>
					<h3>{{galerie.nom_galerie}}</h3>
				</div>
				{% endfor %}
			</div>
		</div>
		{% if galeries|length > 1 %}
		<div id="ctrl-next" class="hidden-phone"></div>
		<div id="ctrl-prec" class="hidden-phone"></div>
		{% endif %}
	</div>
</div>

vitrine/templates/footer.html
<div id="contact">
	{% for contact in contacts %}
	<div id="social"><!--
	--><div>
			<a href="https://www.facebook.com/profile.php?id={{ contact.id_facebook }}"><img src="{{ STATIC_URL }}img/fb.svg" alt="Page Facebook"></a>
		</div><!--
		--><div>
			<a href="http://instagram.com/{{ contact.profile_instagram }}"><img src="{{ STATIC_URL }}img/instagram.svg" alt="Page Instagram"></a>
		</div><!--
		--><div>
			<a href="#"><img src="{{ STATIC_URL }}img/get_google_play.svg" alt="Obtenir l'application android"></a>
		</div><!--
		--></div>
	{% endfor %}
	<div id="bde_info">
		Le BDE vous accueil tous les jours à l'IUT 1! :D
	</div>
	<div id="footer-small">
		<p>Ce site est réalisé par de grands fous. Sans copyright. <a href="{% url 'admin:index'  %}">Administration</a></p>
		<p>Propulsé par Django | Hébergé par alwaysdata | HTML5 | CSS3 | Et d'autres trucs</p>
	</div>
</div>

vitrine/templates/galerie_mobile.html
<!DOCTYPE html>
<html>
<head>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <meta charset="utf-8">
  <title>BDE MMI</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/bde_galerie.css" charset="utf-8">
</head>
<body>
  <header id="navigation">
    {% block header %}
    <nav>
      <a id="back" href="{% url 'vitrine:accueil' %}">
        <img src="{{ STATIC_URL }}img/arrow.svg"/>
      </a>
      <h1>{{galerie.nom}}</h1>
    </nav>
    {% endblock %}
  </header>
  <div id="main">
    <div id="galerie">
      {% for image in galerie.images.all %}
        <div class="galerie-image">
          <a href="{{image.image.url}}"><img src="{{image.image.url}}"/></a>
        </div>
      {%endfor%}
    </div>
  </div>

</body>
</html>

vitrine/templates/gallerie_mobile.html
<!DOCTYPE html>
<html>
<head>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <meta charset="utf-8">
  <title>BDE MMI</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/bde_gallerie.css" charset="utf-8">
</head>
<body>
  <header id="navigation">
    {% block header %}
    <nav>
      <a id="back" href="{% url 'vitrine:accueil' %}"><img src="{{ STATIC_URL }}img/arrow.svg"/></a>
      <h1>{{gallerie.nom}}</h1>
    </nav>
    {% endblock %}
  </header>
  <div id="main">
    <div id="gallerie">
      {% for image in gallerie.images.all %}
        <div class="gallerie-image">
          <a href="{{image.image.url}}"><img src="{{image.image.url}}"/></a>
        </div>
      {%endfor%}
    </div>
  </div>

</body>
</html>

vitrine/templates/team.html
<div id="wrap-team">
	<div id="team">
		<h1>L'équipe</h1>
		{% for membre in membres %}
		<div class="membre">
			<img src="{{ membre.photo.url }}" alt="photo de {{ membre.prenom }} {{ membre.nom }}"/>
			<div class="membre-bande">
				<p>{{ membre.prenom }} {{ membre.nom }}</p>
				<p class="status">{{ membre.status }}</p>
			</div>
		</div>
		{% endfor %}
	</div>
</div>